### ISSUE TITLE
What's the license for this project?

### ISSUE THREAD

**Issue by skeptomai** [SamB/ztools#1]
I'm working on a Rust version of some of these tools and would like to borrow at least from the comments in the code. I'm also making changes to these tools to get the C code to compile cleanly on MacOS and Windows. Would be great to clarify what I can and can't do.  I'd be a fan of Apache 2.0 license if possible, or MIT, or perhaps GPL 2.0?

**Comment by SamB** [comment]
Unfortunately, I didn't write the code and I can't find an explicit license at either of the obvious places to look:
  1. The place I presumably got the source (why else would I have set it as the project's website?),
<https://www.inform-fiction.org/zmachine/ztools.html>,
  2. The if-archive, under <https://www.ifarchive.org/indexes/if-archive/infocom/tools/ztools/>

All I can tell you for sure is that the authors apparently have no problem with people porting the code to whatever OS, since that obviously happened while they were still updating it and they presumably never complained about it (or the if-archive admins would have done something and left a note about it).

Oh, and their identities: https://github.com/SamB/ztools/blob/d7baba7c81f568b29a13f1be4502df6b3920d946/readme.1st#L4-9

... No wait ...

**Comment by SamB** [comment]
Turns out Matthew Russotto is actually still hacking on these tools, and he's doing it over at https://gitlab.com/russotto/ztools!

Hopefully he can actually set you up with a license, or at least some information about whether Mark Howell is still around ...

**Comment by skeptomai** [comment]
Excellent! Thanks for the follow up
